// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate": {
            "post": {
                "description": "Genera un código QR basado en la información proporcionada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QR"
                ],
                "summary": "Generar código QR",
                "parameters": [
                    {
                        "description": "Datos para generar el código QR",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.QRManagement"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Los códigos QR se están generando",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.Error"
                        }
                    }
                }
            }
        },
        "/generate_batch": {
            "post": {
                "description": "Genera múltiples códigos QR basados en la información proporcionada en un archivo CSV",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QR"
                ],
                "summary": "Generar códigos QR en lote",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Archivo CSV con los datos de los invitados | Formato CSV (nombre, invitado_por, parentesco)",
                        "name": "Invitaciones",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Los códigos QR se están generando",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.Error"
                        }
                    }
                }
            }
        },
        "/validate/{id}": {
            "get": {
                "description": "Valida un código QR basado en el ID proporcionado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QR"
                ],
                "summary": "Validar código QR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del código QR",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.QRManagement"
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.QRManagement": {
            "type": "object",
            "properties": {
                "creado": {
                    "type": "string",
                    "example": ""
                },
                "entregado": {
                    "type": "string",
                    "example": ""
                },
                "invitado_por": {
                    "type": "string",
                    "example": "Neifer"
                },
                "nombre": {
                    "type": "string",
                    "example": "Pedro Pacheco"
                },
                "parentesco": {
                    "type": "string",
                    "example": "Familia"
                },
                "sorteo": {
                    "type": "string",
                    "example": ""
                },
                "status": {
                    "type": "string",
                    "example": "Created"
                }
            }
        },
        "entity.Error": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "entity.Success": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/qr-code",
	Schemes:          []string{},
	Title:            "API de Generación y Validación de Códigos QR",
	Description:      "Esta API permite generar y validar códigos QR para invitaciones a eventos.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
