basePath: /api/qr-code
definitions:
  dto.QRManagement:
    properties:
      creado:
        example: ""
        type: string
      entregado:
        example: ""
        type: string
      invitado_por:
        example: Neifer
        type: string
      nombre:
        example: Pedro Pacheco
        type: string
      parentesco:
        example: Familia
        type: string
      sorteo:
        example: ""
        type: string
      status:
        example: Created
        type: string
    type: object
  entity.Error:
    properties:
      data: {}
      message:
        type: string
    type: object
  entity.Success:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
  description: Esta API permite generar y validar códigos QR para invitaciones a eventos.
  title: API de Generación y Validación de Códigos QR
  version: "1.0"
paths:
  /generate:
    post:
      consumes:
      - application/json
      description: Genera un código QR basado en la información proporcionada
      parameters:
      - description: Datos para generar el código QR
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.QRManagement'
      produces:
      - application/json
      responses:
        "200":
          description: Los códigos QR se están generando
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Generar código QR
      tags:
      - QR
  /generate_batch:
    post:
      consumes:
      - multipart/form-data
      description: Genera múltiples códigos QR basados en la información proporcionada
        en un archivo CSV
      parameters:
      - description: Archivo CSV con los datos de los invitados | Formato CSV (nombre,
          invitado_por, parentesco)
        in: formData
        name: Invitaciones
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Los códigos QR se están generando
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Generar códigos QR en lote
      tags:
      - QR
  /validate/{id}:
    get:
      consumes:
      - application/json
      description: Valida un código QR basado en el ID proporcionado
      parameters:
      - description: ID del código QR
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.Success'
            - properties:
                data:
                  $ref: '#/definitions/dto.QRManagement'
                message:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Validar código QR
      tags:
      - QR
swagger: "2.0"
